services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: hex-architecture-laravel-app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=hex_architecture_laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - OCTANE_SERVER=frankenphp
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - hex-architecture-laravel

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: hex-architecture-laravel-worker
    restart: unless-stopped
    working_dir: /app
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=hex_architecture_laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
    command: php artisan queue:work --tries=3 --timeout=90 --sleep=3 --max-jobs=1000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - hex-architecture-laravel

  postgres:
    image: postgres:17-alpine
    container_name: hex-architecture-laravel-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=hex_architecture_laravel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hex-architecture-laravel

  redis:
    image: redis:7-alpine
    container_name: hex-architecture-laravel-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hex-architecture-laravel

networks:
  hex-architecture-laravel:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
